version: '3.9'

services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "hotels_main"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "artyomsql"
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service-container
    ports:
      - "8300:8300"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - eureka-server

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server-container
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service-container
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    ports:
      - "8762:8762"
    depends_on:
      - eureka-server

  reception-service:
    build:
      context: ./reception-service
      dockerfile: Dockerfile
    container_name: reception-service-container
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users-service-container
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    ports:
      - "8200:8200"
    depends_on:
      - eureka-server